apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grafana
  labels:
    component: grafana
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: grafana
  template: 
    metadata:
      labels:
        component: grafana
    spec:
      containers:
      - name: grafana
        image: hkamiya/grafana:000
        imagePullPolicy: Never