apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.2.200-192.168.2.220
#       - 172.17.0.100-172.17.0.200
#     minikubeで取得したアドレスと同じネットワークのアドレスを設定
