apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector: 
    component: wordpress
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 80
    nodePort: 5050
  type: LoadBalancer