apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ftps-replicaset
  labels:
    component: ftps
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: ftps
  template: 
    metadata:
      labels:
        component: ftps
    spec:
      containers:
      - name: ftps
        image: vsftpd:000
        imagePullPolicy: Never