apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  selector: 
    component: ftps
  ports:
  - name: ftpcontrol
    protocol: TCP
    port: 21
    targetPort: 21
    nodePort: 21
  - name: ftpdata1
    protocol: TCP
    port: 60000
    targetPort: 60000
    nodePort: 60000
  - name: ftpdata2
    protocol: TCP
    port: 60001
    targetPort: 60001
    nodePort: 60001
#  type: NodePort
  type: LoadBalancer