---
apiVersion: v1
kind: Secret
metadata:
  name: hoshikawa-mysql
  namespace: default
type: Opaque
data:
  mysql-root-password: "d2tNTXNQRDZERQ=="
  mysql-password: "UUoxSlJGcVFpNQ=="
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hoshikawa-mysql
  namespace: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: hoshikawa-mysql
  namespace: default
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: hoshikawa-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoshikawa-mysql
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hoshikawa-mysql
      release: hoshikawa
  template:
    metadata:
      labels:
        app: hoshikawa-mysql
        release: hoshikawa
    spec:
      serviceAccountName: default
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.31.1"
        imagePullPolicy: "IfNotPresent"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      containers:
      - name: hoshikawa-mysql
        image: "mysql:5"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hoshikawa-mysql
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hoshikawa-mysql
              key: mysql-password
              optional: true
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_DATABASE
          value: ""
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: hoshikawa-mysql