---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    component: mysql
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: mysql
  template: 
    metadata:
      labels:
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:000
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pv-storage
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
