---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    component: mysql
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: mysql
  template: 
    metadata:
      labels:
        component: mysql
    spec:
    #   initContainers:
    #   - name: "remove-lost-found"
    #     image: "busybox:1.31.1"
    #     imagePullPolicy: "IfNotPresent"
    #     command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
    #     volumeMounts:
    #     - name: task-pv-storage
    #       mountPath: /var/lib/mysql
      containers:
      - name: mysql
        image: mysql:000
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim