apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector: 
    component: mysql
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 5000
  type: LoadBalancer