apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector: 
    component: grafana
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 3000
  type: LoadBalancer