---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: influxdb
  labels:
    component: influxdb
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: influxdb
  template: 
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
      - name: influxdb
        image: hkamiya/influxdb:000
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/var/lib/influxdb/"
            name: influxdb-pv-storage
      volumes:
        - name: influxdb-pv-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
