apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
  labels:
    component: wordpress
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: wordpress
  template: 
    metadata:
      labels:
        component: wordpress
    spec:
      containers:
      - name: wordpress
        image: hkamiya/wordpress:000
        imagePullPolicy: Never